/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface AffectMaintenanceToVehicle$Params {
  idMaintenance: number;
  idVehicle: number;
}

export function affectMaintenanceToVehicle(http: HttpClient, rootUrl: string, params: AffectMaintenanceToVehicle$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
  const rb = new RequestBuilder(rootUrl, affectMaintenanceToVehicle.PATH, 'post');
  if (params) {
    rb.query('idMaintenance', params.idMaintenance, {});
    rb.query('idVehicle', params.idVehicle, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      }>;
    })
  );
}

affectMaintenanceToVehicle.PATH = '/gestionStation/maintenance/affectMaintenanceToVehicle';
