/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Maintenance } from '../../models/maintenance';

export interface UpdateMaintenance$Params {
  idMaintenance: number;
      body: Maintenance
}

export function updateMaintenance(http: HttpClient, rootUrl: string, params: UpdateMaintenance$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
  const rb = new RequestBuilder(rootUrl, updateMaintenance.PATH, 'put');
  if (params) {
    rb.query('idMaintenance', params.idMaintenance, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      }>;
    })
  );
}

updateMaintenance.PATH = '/gestionStation/maintenance/updateMaintenance';
