services:
  postgres:
    container_name: postgres-sql-speedyGo
    image: postgres
    environment:
      POSTGRES_USER: onlyDev
      POSTGRES_PASSWORD: onlyDev
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: speedy_go
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-speedyGo
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

  keycloak:
    container_name: keycloak-speedyGo
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: onlyDev
      KEYCLOAK_ADMIN_PASSWORD: onlyDev
    networks:
      - spring-demo
    volumes:
      - ./providers-keycloak:/opt/keycloak/providers  # Montage du dossier contenant les JARs
      - ./providers-keycloak/gson-2.8.9.jar:/opt/keycloak/providers/gson-2.8.9.jar
     # - ./keycloak-themes:/opt/keycloak/themes
    command:
      - "start-dev"

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
