/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Stationdelevery } from '../../models/stationdelevery';

export interface GetStationById$Params {
  id: number;
}

export function getStationById(http: HttpClient, rootUrl: string, params: GetStationById$Params, context?: HttpContext): Observable<StrictHttpResponse<Stationdelevery>> {
  const rb = new RequestBuilder(rootUrl, getStationById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Stationdelevery>;
    })
  );
}

getStationById.PATH = '/api/station-deliveries/getStationById/{id}';
