/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Store } from '../../models/store';

export interface CreateStore$Params {
  name: string;
  description: string;
  contact: string;
  address: string;
  type: string;
      body?: {
'logoUrl'?: Blob;
'backgroundImageUrl'?: Blob;
}
}

export function createStore(http: HttpClient, rootUrl: string, params: CreateStore$Params, context?: HttpContext): Observable<StrictHttpResponse<Store>> {
  const rb = new RequestBuilder(rootUrl, createStore.PATH, 'post');
  if (params) {
    rb.query('name', params.name, {});
    rb.query('description', params.description, {});
    rb.query('contact', params.contact, {});
    rb.query('address', params.address, {});
    rb.query('type', params.type, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Store>;
    })
  );
}

createStore.PATH = '/store';
