/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';
import {PaginatedVehicleRentalResponse} from "../../models/PaginatedVehicleRentalResponse";


export interface GetAllVehicleRental$Params {
  page?: number;
  size?: number;
  sortBy?: string;
  sortOrder?: string;
}


export function getAllVehicleRental(
  http: HttpClient,
  rootUrl: string,
  params?: GetAllVehicleRental$Params,
  context?: HttpContext
): Observable<StrictHttpResponse<PaginatedVehicleRentalResponse>> {
  const rb = new RequestBuilder(rootUrl, getAllVehicleRental.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
    rb.query('sortBy', params.sortBy, {});
    rb.query('sortOrder', params.sortOrder, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<PaginatedVehicleRentalResponse> => r instanceof HttpResponse),
    map((r: HttpResponse<PaginatedVehicleRentalResponse>) => {
      return r as StrictHttpResponse<PaginatedVehicleRentalResponse>;
    })
  );
}
getAllVehicleRental.PATH = '/gestionStation/vehicleRental/getAllVehicleRental';
