/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Carpooling } from '../models/carpooling';
export interface BookingSeats {
  carpooling?: Carpooling;
  id?: number;
  seatsRequested?: number;
  status?: string;
}
