/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface Carpooling {
  arrivalLocation?: string;
  departLocation?: string;
  id?: number;
  pricePerSeat?: number;
  seatsAvailable?: number;
  status?: string;
  time?: string;
  user?: User;
}
