/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Message } from '../models/message';
export interface Chat {
  id?: number;
  messages?: Array<Message>;
}
