/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface Comment {
  content?: string;
  createdDate?: string;
  id?: number;
  lastModifiedDate?: string;
  user?: User;
}
