/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Order } from '../models/order';
import { User } from '../models/user';
export interface Delivery {
  additionalNotes?: string;
  client?: User;
  courier?: User;
  deliveryAddress?: string;
  deliveryFee?: number;
  deliveryLatitude?: number;
  deliveryLongitude?: number;
  deliveryTime?: string;
  deliveryType?: string;
  distance?: number;
  estimatedTime?: number;
  id?: number;
  isDeliveredOnTime?: boolean;
  isFragile?: boolean;
  order?: Order;
  paymentStatus?: string;
  pickupAddress?: string;
  pickupLatitude?: number;
  pickupLongitude?: number;
  pickupTime?: string;
  status?: string;
  trackingNumber?: string;
}
