/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Maintenance {
  cost?: number;
  estimatedCompletionTime?: string;
  id?: number;
  maintenanceType?: string;
  scheduledDate?: string;
  status?: 'Pending' | 'In_progress' | 'Completed';
  technicianName?: string;
  emailTechnician?:string ;
}
