/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MaintenanceHistory {
  cost?: number;
  date?: string;
  description?: string;
  id?: number;
  partsReplaced?: string;
  repairDuration?: number;
}
