/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Order } from '../models/order';
export interface OrderItem {
  id?: number;
  order?: Order;
  price?: number;
  productId?: number;
  productName?: string;
  quantity?: number;
  totalPrice?: number;
}
