/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OrderRequest {
  deliveryMethod?: string;
  paymentConfirmed?: boolean;
  paymentMethod?: string;
  phoneNumber?: string;
  shippingAddress?: string;
}
