/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrderItem } from '../models/order-item';
import { User } from '../models/user';
export interface Order {
  deliveryMethod?: string;
  id?: number;
  orderDate?: string;
  orderItems?: Array<OrderItem>;
  orderStatus?: 'PENDING' | 'PAID' | 'SHIPPED' | 'DELIVERED' | 'CANCELED' | 'REFUNDED';
  paymentConfirmed?: boolean;
  paymentMethod?: string;
  paymentStatus?: string;
  phoneNumber?: string;
  shippingAddress?: string;
  totalAmount?: number;
  user?: User;
}
