/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface Panier {
  id?: number;
  produits?: {
[key: string]: number;
};
  status?: 'OPEN' | 'PAID' | 'CANCELLED';
  totalPrice?: number;
  user?: User;
}
