/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Product } from '../models/product';
import { User } from '../models/user';
export interface Parcel {
  customerParcel?: User;
  driverParcel?: User;
  id?: number;
  products?: Array<Product>;
  typeParcel?: 'ClOTHING' | 'FRAGILE' | 'FOOD';
}
