/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PostRequest {
  content?: string;
  id?: number;
  mediaUrl?: string;
  status?: 'ACTIF' | 'DELETED' | 'ARCHIVED';
  title?: string;
  visibility?: boolean;
}
