/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductResponse {
  available?: boolean;
  description?: string;
  discount?: number;
  id?: number;
  imageUrl?: string;
  name?: string;
  price?: number;
  rating?: number;
  stockQuantity?: number;
}
