/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Delivery } from '../models/delivery';
import { User } from '../models/user';
export interface RatingAndFeedback {
  customer?: User;
  delivery?: Delivery;
  driver?: User;
  feedback?: string;
  id?: number;
  rating?: number;
  submittedAt?: string;
}
