/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface Reaction {
  createdDate?: string;
  id?: number;
  lastModifiedDate?: string;
  typeReaction?: 'LIKE' | 'LOVE' | 'HAHA' | 'SAD' | 'ANGRY' | 'WOW';
  user?: User;
}
