/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Carpooling } from '../models/carpooling';
import { Payment } from '../models/payment';
import { Taxi } from '../models/taxi';
import { Trip } from '../models/trip';
import { User } from '../models/user';
export interface ReservationTrip {
  carpooling?: Carpooling;
  carpoolingUsers?: Array<User>;
  driver?: User;
  id?: number;
  payment?: Payment;
  taxi?: Taxi;
  taxiUser?: User;
  trip?: Trip;
}
