/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Product } from '../models/product';
import { User } from '../models/user';
export interface Review {
  customerReview?: User;
  driverReview?: User;
  id?: number;
  product?: Product;
}
