/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Post } from '../models/post';
export interface Sharing {
  comment?: string;
  createdDate?: string;
  id?: number;
  lastModifiedDate?: string;
  post?: Post;
  visibility?: boolean;
}
