/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface Store {
  address?: string;
  backgroundImageUrl?: string;
  contact?: string;
  description?: string;
  id?: number;
  logoUrl?: string;
  name?: string;
  partner?: User;
  status?: 'ACTIVE' | 'FERMEE' | 'SUSPENDUE';
  type?: 'MAGASIN' | 'RESTAURANT' | 'PHARMACY' | 'ELECTRONICS';
}
