/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SubscriptionDto {
  durationInDays?: number;
  endDate?: string;
  id?: number;
  isActive?: boolean;
  planName?: string;
  price?: number;
  startDate?: string;
  subscriberEmail?: string;
}
