/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface SupportTicket {
  customerSupportTicket?: User;
  driverSupportTicket?: User;
  id?: number;
}
