/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Taxi {
  available?: boolean;
  id?: number;
  licensePlate?: string;
  model?: string;
  typeTaxi?: 'PREMIUM' | 'STANDARD';
  othermodel?:string;
}
