/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Payment } from '../models/payment';
export interface Transaction {
  amount?: number;
  createdTimestamp?: number;
  currency?: string;
  id?: number;
  payment?: Payment;
  status?: string;
  transactionId?: string;
  transactionType?: string;
}
