/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface Trip {
  createdAt?: string;
  customer?: User;
  distance?: number;
  driver?: User;
  dropoffLocation?: string;
  fare?: number;
  id?: number;
  pickupLocation?: string;
}
