/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Chat } from '../models/chat';
import { EventPromotion } from '../models/event-promotion';
import { LoyaltyProgram } from '../models/loyalty-program';
import { Notification } from '../models/notification';
import { Parcel } from '../models/parcel';
import { Post } from '../models/post';
import { Product } from '../models/product';
import { Rental } from '../models/rental';
import { ReservationTrip } from '../models/reservation-trip';
import { Review } from '../models/review';
import { Station } from '../models/station';
import { SupportTicket } from '../models/support-ticket';
import { Trip } from '../models/trip';
export interface User {
  active?: boolean;
  address?: string;
  availability?: boolean;
  chatsReceived?: Array<Chat>;
  chatsSender?: Array<Chat>;
  createdDate?: string;
  criminalRecord?: string;
  email?: string;
  eventPromotionsCustomer?: Array<EventPromotion>;
  eventPromotionsPartner?: Array<EventPromotion>;
  firstName?: string;
  id?: string;
  insurance?: string;
  lastModifiedDate?: string;
  lastName?: string;
  licence?: string;
  loyaltyProgramsCustomer?: Array<LoyaltyProgram>;
  loyaltyProgramsPartner?: Array<LoyaltyProgram>;
  notifications?: Array<Notification>;
  parcelsCustomer?: Array<Parcel>;
  parcelsDriver?: Array<Parcel>;
  partnerType?: 'RESTAURANT' | 'STORE' | 'PHARMACY';
  password?: string;
  postListReceiver?: Array<Post>;
  postSender?: Array<Post>;
  productsCustomer?: Array<Product>;
  productsPartner?: Array<Product>;
  rating?: number;
  rentals?: Array<Rental>;
  reservationTripDriver?: ReservationTrip;
  reservationTripsCarpooling?: Array<ReservationTrip>;
  reservationTripsTaxi?: Array<ReservationTrip>;
  reviewsCustomer?: Array<Review>;
  reviewsDriver?: Array<Review>;
  role?: 'DRIVER' | 'PARTNER' | 'CUSTOMER';
  stationManagment?: Station;
  supportTicketsCustomer?: Array<SupportTicket>;
  supportTicketsDriver?: Array<SupportTicket>;
  tripsCustomer?: Array<Trip>;
  tripsDriver?: Array<Trip>;
}
