/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Stationdelevery } from '../models/stationdelevery';
export interface Vehicule {
  available?: boolean;
  capacity?: number;
  id?: number;
  model?: string;
  stationdelevery?: Stationdelevery;
  type?: 'CAR' | 'MOTORCYCLE' | 'TRUCK' | 'BYCICLE';
  vitesse?: number;
}
