/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReservationCarpool } from '../../models/reservation-carpool';

export interface AcceptReservation$Params {
  id: number;
}

export function acceptReservation(http: HttpClient, rootUrl: string, params: AcceptReservation$Params, context?: HttpContext): Observable<StrictHttpResponse<ReservationCarpool>> {
  const rb = new RequestBuilder(rootUrl, acceptReservation.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ReservationCarpool>;
    })
  );
}

acceptReservation.PATH = '/reservationCarpool/accept/{id}';
