/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReservationCarpool } from '../../models/reservation-carpool';

export interface FindByRequestedPrice$Params {
  requestedPrice: number;
}

export function findByRequestedPrice(http: HttpClient, rootUrl: string, params: FindByRequestedPrice$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ReservationCarpool>>> {
  const rb = new RequestBuilder(rootUrl, findByRequestedPrice.PATH, 'get');
  if (params) {
    rb.path('requestedPrice', params.requestedPrice, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ReservationCarpool>>;
    })
  );
}

findByRequestedPrice.PATH = '/reservationCarpool/searchByPrice/{requestedPrice}';
