/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface AffecterStationDestinationRental$Params {
  rentalId: number;
  idDestination: number;
}

export function affecterStationDestinationRental(http: HttpClient, rootUrl: string, params: AffecterStationDestinationRental$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
  const rb = new RequestBuilder(rootUrl, affecterStationDestinationRental.PATH, 'post');
  if (params) {
    rb.query('rentalId', params.rentalId, {});
    rb.query('idDestination', params.idDestination, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      }>;
    })
  );
}

affecterStationDestinationRental.PATH = '/gestionStation/rental/affecterStationDestinationRental';
