/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface AffecterVehicleRentalToRental$Params {
  idVehicleRental: number;
  idRental: number;
}

export function affecterVehicleRentalToRental(http: HttpClient, rootUrl: string, params: AffecterVehicleRentalToRental$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
  const rb = new RequestBuilder(rootUrl, affecterVehicleRentalToRental.PATH, 'post');
  if (params) {
    rb.query('idVehicleRental', params.idVehicleRental, {});
    rb.query('idRental', params.idRental, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      }>;
    })
  );
}

affecterVehicleRentalToRental.PATH = '/gestionStation/rental/affecterVehicleRentalToRental';
