/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { VehiculeControllerService } from './services/vehicule-controller.service';
import { TaxiControllerService } from './services/taxi-controller.service';
import { StroreControllerService } from './services/strore-controller.service';
import { ReservationTaxiControllerService } from './services/reservation-taxi-controller.service';
import { ReservationCarpoolControllerService } from './services/reservation-carpool-controller.service';
import { PromotionAndEventService } from './services/promotion-and-event.service';
import { ProductControllerService } from './services/product-controller.service';
import { PostService } from './services/post.service';
import { OrderControllerService } from './services/order-controller.service';
import { VehicleRentalControllerService } from './services/vehicle-rental-controller.service';
import { StationControllerService } from './services/station-controller.service';
import { RentalControllerService } from './services/rental-controller.service';
import { MaintenanceHistoryControllerService } from './services/maintenance-history-controller.service';
import { MaintenanceControllerService } from './services/maintenance-controller.service';
import { CarpoolingControllerService } from './services/carpooling-controller.service';
import { BookingSeatsControllerService } from './services/booking-seats-controller.service';
import { SubscriptionControllerService } from './services/subscription-controller.service';
import { StationDeliveryControllerService } from './services/station-delivery-controller.service';
import { RatingAndFeedbackControllerService } from './services/rating-and-feedback-controller.service';
import { DeliveryControllerService } from './services/delivery-controller.service';
import { PanierControllerService } from './services/panier-controller.service';
import { PaymentControllerService } from './services/payment-controller.service';
import { UserService } from './services/user.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    VehiculeControllerService,
    TaxiControllerService,
    StroreControllerService,
    ReservationTaxiControllerService,
    ReservationCarpoolControllerService,
    PromotionAndEventService,
    ProductControllerService,
    PostService,
    OrderControllerService,
    VehicleRentalControllerService,
    StationControllerService,
    RentalControllerService,
    MaintenanceHistoryControllerService,
    MaintenanceControllerService,
    CarpoolingControllerService,
    BookingSeatsControllerService,
    SubscriptionControllerService,
    StationDeliveryControllerService,
    RatingAndFeedbackControllerService,
    DeliveryControllerService,
    PanierControllerService,
    PaymentControllerService,
    UserService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
