/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { VehiculeControllerService } from './services/vehicule-controller.service';
export { TaxiControllerService } from './services/taxi-controller.service';
export { StroreControllerService } from './services/strore-controller.service';
export { ReservationTaxiControllerService } from './services/reservation-taxi-controller.service';
export { ReservationCarpoolControllerService } from './services/reservation-carpool-controller.service';
export { PromotionAndEventService } from './services/promotion-and-event.service';
export { ProductControllerService } from './services/product-controller.service';
export { PostService } from './services/post.service';
export { OrderControllerService } from './services/order-controller.service';
export { VehicleRentalControllerService } from './services/vehicle-rental-controller.service';
export { StationControllerService } from './services/station-controller.service';
export { RentalControllerService } from './services/rental-controller.service';
export { MaintenanceHistoryControllerService } from './services/maintenance-history-controller.service';
export { MaintenanceControllerService } from './services/maintenance-controller.service';
export { CarpoolingControllerService } from './services/carpooling-controller.service';
export { BookingSeatsControllerService } from './services/booking-seats-controller.service';
export { SubscriptionControllerService } from './services/subscription-controller.service';
export { StationDeliveryControllerService } from './services/station-delivery-controller.service';
export { RatingAndFeedbackControllerService } from './services/rating-and-feedback-controller.service';
export { DeliveryControllerService } from './services/delivery-controller.service';
export { PanierControllerService } from './services/panier-controller.service';
export { PaymentControllerService } from './services/payment-controller.service';
export { UserService } from './services/user.service';
