/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Panier } from '../../models/panier';

export interface AddPanierForCurrentUser$Params {
}

export function addPanierForCurrentUser(http: HttpClient, rootUrl: string, params?: AddPanierForCurrentUser$Params, context?: HttpContext): Observable<StrictHttpResponse<Panier>> {
  const rb = new RequestBuilder(rootUrl, addPanierForCurrentUser.PATH, 'post');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Panier>;
    })
  );
}

addPanierForCurrentUser.PATH = '/panier/add';
