/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Panier } from '../../models/panier';

export interface AddProductToPanier$Params {
  productId: number;
  quantity: number;
}

export function addProductToPanier(http: HttpClient, rootUrl: string, params: AddProductToPanier$Params, context?: HttpContext): Observable<StrictHttpResponse<Panier>> {
  const rb = new RequestBuilder(rootUrl, addProductToPanier.PATH, 'post');
  if (params) {
    rb.path('productId', params.productId, {});
    rb.path('quantity', params.quantity, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Panier>;
    })
  );
}

addProductToPanier.PATH = '/panier/add-product/{productId}/{quantity}';
