/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Panier } from '../../models/panier';

export interface GetPanierForCurrentUser$Params {
}

export function getPanierForCurrentUser(http: HttpClient, rootUrl: string, params?: GetPanierForCurrentUser$Params, context?: HttpContext): Observable<StrictHttpResponse<Panier>> {
  const rb = new RequestBuilder(rootUrl, getPanierForCurrentUser.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Panier>;
    })
  );
}

getPanierForCurrentUser.PATH = '/panier/current';
