/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Carpooling } from '../../models/carpooling';

export interface UpdateCarpool$Params {
  id: number;
      body: Carpooling
}

export function updateCarpool(http: HttpClient, rootUrl: string, params: UpdateCarpool$Params, context?: HttpContext): Observable<StrictHttpResponse<Carpooling>> {
  const rb = new RequestBuilder(rootUrl, updateCarpool.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Carpooling>;
    })
  );
}

updateCarpool.PATH = '/carpooling/{id}';
