/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { addVehicle } from '../fn/vehicule-controller/add-vehicle';
import { AddVehicle$Params } from '../fn/vehicule-controller/add-vehicle';
import { deleteVehicle } from '../fn/vehicule-controller/delete-vehicle';
import { DeleteVehicle$Params } from '../fn/vehicule-controller/delete-vehicle';
import { getAllVehicles } from '../fn/vehicule-controller/get-all-vehicles';
import { GetAllVehicles$Params } from '../fn/vehicule-controller/get-all-vehicles';
import { getVehicleById } from '../fn/vehicule-controller/get-vehicle-by-id';
import { GetVehicleById$Params } from '../fn/vehicule-controller/get-vehicle-by-id';
import { updateVehicle } from '../fn/vehicule-controller/update-vehicle';
import { UpdateVehicle$Params } from '../fn/vehicule-controller/update-vehicle';
import { Vehicule } from '../models/vehicule';

@Injectable({ providedIn: 'root' })
export class VehiculeControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `updateVehicle()` */
  static readonly UpdateVehiclePath = '/vehicle/updateVehicle/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateVehicle()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateVehicle$Response(params: UpdateVehicle$Params, context?: HttpContext): Observable<StrictHttpResponse<Vehicule>> {
    return updateVehicle(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateVehicle$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateVehicle(params: UpdateVehicle$Params, context?: HttpContext): Observable<Vehicule> {
    return this.updateVehicle$Response(params, context).pipe(
      map((r: StrictHttpResponse<Vehicule>): Vehicule => r.body)
    );
  }

  /** Path part for operation `addVehicle()` */
  static readonly AddVehiclePath = '/vehicle/addVehicle';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addVehicle()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addVehicle$Response(params: AddVehicle$Params, context?: HttpContext): Observable<StrictHttpResponse<Vehicule>> {
    return addVehicle(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addVehicle$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addVehicle(params: AddVehicle$Params, context?: HttpContext): Observable<Vehicule> {
    return this.addVehicle$Response(params, context).pipe(
      map((r: StrictHttpResponse<Vehicule>): Vehicule => r.body)
    );
  }

  /** Path part for operation `getVehicleById()` */
  static readonly GetVehicleByIdPath = '/vehicle/getVehicleById/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getVehicleById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getVehicleById$Response(params: GetVehicleById$Params, context?: HttpContext): Observable<StrictHttpResponse<Vehicule>> {
    return getVehicleById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getVehicleById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getVehicleById(params: GetVehicleById$Params, context?: HttpContext): Observable<Vehicule> {
    return this.getVehicleById$Response(params, context).pipe(
      map((r: StrictHttpResponse<Vehicule>): Vehicule => r.body)
    );
  }

  /** Path part for operation `getAllVehicles()` */
  static readonly GetAllVehiclesPath = '/vehicle/getAllVehicles/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllVehicles()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllVehicles$Response(params?: GetAllVehicles$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Vehicule>>> {
    return getAllVehicles(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllVehicles$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllVehicles(params?: GetAllVehicles$Params, context?: HttpContext): Observable<Array<Vehicule>> {
    return this.getAllVehicles$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Vehicule>>): Array<Vehicule> => r.body)
    );
  }

  /** Path part for operation `deleteVehicle()` */
  static readonly DeleteVehiclePath = '/vehicle/deleteVehicle/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteVehicle()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteVehicle$Response(params: DeleteVehicle$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteVehicle(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteVehicle$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteVehicle(params: DeleteVehicle$Params, context?: HttpContext): Observable<void> {
    return this.deleteVehicle$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
