/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Delivery } from '../../models/delivery';

export interface CreateDelivery$Params {
      body: Delivery
}

export function createDelivery(http: HttpClient, rootUrl: string, params: CreateDelivery$Params, context?: HttpContext): Observable<StrictHttpResponse<Delivery>> {
  const rb = new RequestBuilder(rootUrl, createDelivery.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Delivery>;
    })
  );
}

createDelivery.PATH = '/api/deliveries/createDelivery';
