/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Delivery } from '../../models/delivery';

export interface GetDeliveryById$Params {
  id: number;
}

export function getDeliveryById(http: HttpClient, rootUrl: string, params: GetDeliveryById$Params, context?: HttpContext): Observable<StrictHttpResponse<Delivery>> {
  const rb = new RequestBuilder(rootUrl, getDeliveryById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Delivery>;
    })
  );
}

getDeliveryById.PATH = '/api/deliveries/getDeliveryById/{id}';
