/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Delivery } from '../../models/delivery';

export interface GetAllDeliveries$Params {
}

export function getAllDeliveries(http: HttpClient, rootUrl: string, params?: GetAllDeliveries$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Delivery>>> {
  const rb = new RequestBuilder(rootUrl, getAllDeliveries.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Delivery>>;
    })
  );
}

getAllDeliveries.PATH = '/api/deliveries/getAllDeliveries';
