/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface AffectationReservationTaxi$Params {
  idDriverTaxi: string;
  idReservationTaxi: number;
}

export function affectationReservationTaxi(http: HttpClient, rootUrl: string, params: AffectationReservationTaxi$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
  const rb = new RequestBuilder(rootUrl, affectationReservationTaxi.PATH, 'post');
  if (params) {
    rb.query('idDriverTaxi', params.idDriverTaxi, {});
    rb.query('idReservationTaxi', params.idReservationTaxi, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      }>;
    })
  );
}

affectationReservationTaxi.PATH = '/reservationTaxi/affectationReservationTaxi';
