/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Subscription } from '../../models/subscription';

export interface CreateSubscription$Params {
  email: string;
      body: Subscription
}

export function createSubscription(http: HttpClient, rootUrl: string, params: CreateSubscription$Params, context?: HttpContext): Observable<StrictHttpResponse<Subscription>> {
  const rb = new RequestBuilder(rootUrl, createSubscription.PATH, 'post');
  if (params) {
    rb.query('email', params.email, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Subscription>;
    })
  );
}

createSubscription.PATH = '/api/subscriptions/createSubscription';
