/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Subscription } from '../../models/subscription';

export interface GetSubscriptionById$Params {
  id: number;
}

export function getSubscriptionById(http: HttpClient, rootUrl: string, params: GetSubscriptionById$Params, context?: HttpContext): Observable<StrictHttpResponse<Subscription>> {
  const rb = new RequestBuilder(rootUrl, getSubscriptionById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Subscription>;
    })
  );
}

getSubscriptionById.PATH = '/api/subscriptions/getSubscriptionById/{id}';
