/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SubscriptionDto } from '../../models/subscription-dto';

export interface GetAllSubscriptions$Params {
}

export function getAllSubscriptions(http: HttpClient, rootUrl: string, params?: GetAllSubscriptions$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SubscriptionDto>>> {
  const rb = new RequestBuilder(rootUrl, getAllSubscriptions.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SubscriptionDto>>;
    })
  );
}

getAllSubscriptions.PATH = '/api/subscriptions/getAllSubscriptions';
