/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EventPromotion } from '../../models/event-promotion';

export interface GetPromotionById$Params {
  pvId: number;
}

export function getPromotionById(http: HttpClient, rootUrl: string, params: GetPromotionById$Params, context?: HttpContext): Observable<StrictHttpResponse<EventPromotion>> {
  const rb = new RequestBuilder(rootUrl, getPromotionById.PATH, 'get');
  if (params) {
    rb.path('pvId', params.pvId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EventPromotion>;
    })
  );
}

getPromotionById.PATH = '/pv/{pvId}';
