/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Product } from '../../models/product';

export interface AddProduct$Params {
  name: string;
  price: number;
  description: string;
  stockQuantity: number;
  available: boolean;
  discount?: number;
  rating?: number;
      body?: {
'image': Blob;
}
}

export function addProduct(http: HttpClient, rootUrl: string, params: AddProduct$Params, context?: HttpContext): Observable<StrictHttpResponse<Product>> {
  const rb = new RequestBuilder(rootUrl, addProduct.PATH, 'post');
  if (params) {
    rb.query('name', params.name, {});
    rb.query('price', params.price, {});
    rb.query('description', params.description, {});
    rb.query('stockQuantity', params.stockQuantity, {});
    rb.query('available', params.available, {});
    rb.query('discount', params.discount, {});
    rb.query('rating', params.rating, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Product>;
    })
  );
}

addProduct.PATH = '/product';
